on: push
jobs: 
  secrets: 
  runs-on: ubuntu-latest
  steps: 
  - run: echo $MY_SECRET
    env:
      MY_VAR: ${{ secrets.MY_SECRET }}$
  - run: |
      import os
      print(len(os.getenv('MY_SECRET')))
    shell: python
