name: Secrets
on:
  push:
    branches:
      - main
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Echo secret value
        run: echo ${{ secrets.MY_SECRET }}
      - name: Print secret length using Python
        run: |
          python -c "import os; print(len(os.getenv('MY_SECRET'))); print('hello world')"
        shell: bash
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}